[package]
name = "alloy-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
alloy-core = { path = "../alloy-core" }
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

